server:
  port: 8093


  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1

management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include:
          - "*"
          - info

info:
  application:
    name: '@name@'
    description: This is a functional SpringBoot Project 2.0 that reads 2 csv files and creates a crud based on it.
    version: v1
    spring-boot-version: 2.6.4
